#!/bin/bash

RUNTIME_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
BIN_DIR="$RUNTIME_DIR/bin"

"$BIN_DIR/java" \
  --module-path "$RUNTIME_DIR/dependencies" \
  --module "org.mal_lang.compiler.cli" \
  $@
